version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: electricity-postgres
    environment:
      POSTGRES_DB: electricity
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    networks:
      - electricity-network

  backend:
    build: .
    container_name: electricity-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/electricity
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: admin
      JWT_SECRET: MySuperSecretKeyMySuperSecretKeyMySuperSecretKey
    networks:
      - electricity-network

  frontend:
    build:
      context: ../frontend-seba-electricity-bot/electricity-bot/
      dockerfile: Dockerfile
    container_name: electricity-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
    networks:
      - electricity-network

networks:
  electricity-network:
